feat: 优化日志

diff --git a/fnpack/cmd/main b/fnpack/cmd/main
--- a/fnpack/cmd/main
+++ b/fnpack/cmd/main
@@ -7,7 +7,11 @@ PID_FILE="${TRIM_PKGVAR}/app.pid"
 CMD="${TRIM_APPDEST}/bin/docker-updater --fnos"
 
 log_msg() {
-    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" >> ${LOG_FILE}
+    echo "$(date '+%Y-%m-%d %H:%M:%S') [INFO] $1" >> ${LOG_FILE}
+}
+
+log_err() {
+    echo "$(date '+%Y-%m-%d %H:%M:%S') [ERROR] $1" >> ${LOG_FILE}
 }
 
 start_process() {
@@ -15,47 +19,54 @@ start_process() {
         return 0
     fi
 
-    log_msg "Starting process ..."
-    # run cmd to start process
+    log_msg "正在启动应用进程..."
+    # 启动应用进程
     bash -c "${CMD}" >> ${LOG_FILE} 2>&1 &
-    # write pid to pidfile
-    printf "%s" "$!" > ${PID_FILE}
-    # log_msg "CMD = ${CMD}"
-    # log_msg "pid = $!"
+    local pid=$!
+    printf "%s" "${pid}" > ${PID_FILE}
+
+    # 探活检测启动状态
+    sleep 1
+    if ! check_process "${pid}"; then
+        log_err "应用进程启动失败 (进程 PID: ${pid} 意外退出)。"
+        rm -f "${PID_FILE}"
+        return 1
+    fi
+
     return 0
 }
 
 stop_process() {
-    log_msg "Stopping process ..."
+    log_msg "正在停止应用进程..."
 
     if [ -r "${PID_FILE}" ]; then
         pid=$(head -n 1 "${PID_FILE}" | tr -d '[:space:]')
         
-        log_msg "pid=${pid}"
+        log_msg "检测到运行中的进程 PID: ${pid}"
         if ! check_process "${pid}"; then
-            # process not exist, delete pidfile
+            # 进程不存在，清理无效 PID 文件
             rm -f "${PID_FILE}"
-            log_msg "remove pid file 1"
+            log_msg "进程不存在，已清理残留 PID 文件"
             return
         fi
 
-        log_msg "send TERM signal to PID:${pid}..."
+        log_msg "正在向进程 PID: ${pid} 发送 SIGTERM 停止信号..."
         kill -TERM ${pid} >> ${LOG_FILE} 2>&1
 
         local count=0
         while check_process "${pid}" && [ $count -lt 10 ]; do
             sleep 1
             count=$((count + 1))
-            log_msg "waiting process terminal... (${count}s/10s)"
+            log_msg "等待进程终止... (${count}秒/10秒)"
         done
 
         if check_process "${pid}"; then
-            log_msg "send KILL signal to PID:${pid}..."
+            log_err "进程 PID: ${pid} 未在 10 秒超时内停止，已发送 SIGKILL 强制杀掉进程。"
             kill -KILL "${pid}"
             sleep 1
             rm -f "${PID_FILE}"
         else
-            log_msg "process killed... "
+            log_msg "应用进程已成功停止。"
         fi
     fi
 
